server:
  servlet:
    context-path: /pikes/command

spring:
  application:
    name: pike_cqrs_read
  cloud:
    stream:
      bindings:
        output:
          destination: pike-events
          producer.header-mode: raw
          contentType: application/json
        input:
          destination: pike-events
          consumer.header-mode: raw
          contentType: application/json
          group: pike-events-group
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
        binder:
          brokers: localhost:9092




