server:
  servlet:
    context-path: /bikes
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: bike-events
          consumer.header-mode: raw
          group: summary-bike-events-11
          content-type: application/json
      kafka:
        binder:
          headers: event-type,kafka_messageKey


