server:
  servlet:
    context-path: /bikes
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: bike-events
          consumer.headerMode: headers
          group: summary-bike-events
          content-type: application/json
      kafka:
        binder:
          headers: event_type,kafka_messageKey


