server:
  servlet:
    context-path: /bike
  port: 8080

spring:
  gateway:
    routes:
      - id: route_1
        uri: lb://localhost:8081/bike
        predicates:
          - Path=/command
      - id: route_2
        uri: lb://localhost:8082/bike
        predicates:
          - Path=/query
  application:
    name: oocl-service


