server:
  servlet:
    context-path: /bikes
  port: 8081

spring:
  application:
    name: bike_cqrs_read
  cloud:
    stream:
      bindings:
        output:
          destination: bike-events
          producer.headerMode: headers
          contentType: application/json
        input:
          destination: bike-events
          consumer.headerMode: headers
          contentType: application/json
          group: bike-events-group
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
        binder:
          brokers: localhost:9092
          headers: event_type,kafka_messageKey
